version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
