name: Run pre-release checks

on:
  release:
    types: [created]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: "Build Docker image and run smoke test"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
      - name: Run tests
        run: |
          docker run \
            -v $PWD:/workspace \
            --pull=never \
            --rm ${{ steps.meta.outputs.tags }} \
            docker run --rm test_img:latest tuned-lens --help
  build-n-publish-python-package:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
