name: Pre-merge checks

on:
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files

  build-and-test:
    name: "Build Docker image and test the code within it"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        # This is required for now see
        # https://github.com/docker/build-push-action/issues/163
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host
      - name: Build Docker image
        # Note that we do NOT push here
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run unit tests within Docker container
        run: docker run ${{ steps.meta.outputs.tags }}
