name: Create release

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate-tag:
    name: Validate tag
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install toml
        run: pip install toml
      - name: Add version from pyproject.toml to environment vars
        run: |
          PROJECT_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      - name: Check if tag version matches project version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          echo $TAG
          echo $PROJECT_VERSION
          if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi
  build-and-test:
    name: "Build Docker image and run smoke test"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: prod
          tags: ${{ steps.meta.outputs.tags }}
      - name: Run tests
        run: |
          docker run \
            --pull=never \
            --rm ${{ steps.meta.outputs.tags }} \
            tuned-lens --help
  build-n-publish-python-package:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - validate-tag
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
  create-draft-release:
    name: Create a draft release
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - build-n-publish-python-package
    steps:
    - name: Create a draft release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
