name: Pre-merge checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files
  # For reference https://docs.docker.com/build/ci/github-actions/share-image-jobs/
  build-test-img:
    name: "Build Docker image for testing"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        # Note that we do NOT push here
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
          tags: test_image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests in docker image
        run: |
          docker run --pull never test_image:latest
