name: Pre-merge checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files

  build-and-test:
    name: "Build Docker image and test the code within it"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker images
        run: docker build . --target test --tag $GITHUB_REF
      - name: Run tests within Docker container
        run: docker run $GITHUB_REF
