name: Pre-merge checks

on:
  pull_request:
    branches: [ "main" ]


jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files
  test-docs:
    name: "Run build docs and tune doctests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install dependences
        run: |
          pip install -e ".[docs]"
      - name: Ensure no warnings
        run: |
          python -m sphinx -W docs docs/_build
      - name: Run doc-tests
        run: |
          cd docs && make doctest
  build-and-test:
    name: "Build Docker image and run unit tests within it"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
          tags: unit_test_img:latest
      - name: Run tests
        run: |
          docker run \
            -v $PWD:/workspace \
            --pull=never \
            --rm unit_test_img:latest \
            pytest
